### ISSUE TITLE
Responsiveness: mobile device display needs improvement

### ISSUE THREAD

**Issue by yharich** [yellowhouseassociates/dashboard-ns#35]

**Comment by Teranode** [comment]
like what exactly are you looking into for "improvement"? (Cause im bored and want to do something)

**Comment by yharich** [comment]
![image](https://cloud.githubusercontent.com/assets/5408851/7624888/22b2de8c-f9ad-11e4-968a-7eec8d1f016e.png)

**Comment by yharich** [comment]
To start with, I'd like the red circled areas to be responsive.  While the bootstrap stuff surrounding it responds well, I didn't apply any @media-query stuff to things inside the grid such as font sizes and image sizing.

If you can make another stylesheet and put the standard device size @media-query stuff it in and make some classes to be applied the the circled areas, that would be great.  Or if Bootstrap already has classes for that, point them out and apply them.

**Comment by yharich** [comment]
The second part is how to configure AmCharts and Highcharts to respond better to different screen sizes.  The containers the charts reside in size themselves fine, it is the fonts and lines and such in the graph itself that end up all scrunched together on smaller device screens.

For example, on table or phone, the mountain chart in the screen up above has its category axis (the days of the month) pushed together too densely to read.  I thought I had read in AmCharts or Highcharts that you could apply classes to the chart based on @media-queries but I haven't had time to investigate yet.

If you are up for that challenge, the critical chart to investigate this for is the mountain chart, which is using the AmCharts library.

**Comment by Teranode** [comment]
I'll look into the red circled areas, though i dont know much about amCharts to be touching it >_>. But I'll take a look to see what i can come up with.

**Comment by Teranode** [comment]
too many individual font sizes for the header portion:
http://prntscr.com/75ob4d

Rather why not create a global container for that one section, so we are able to resize fonts based on screen size?

**Comment by Teranode** [comment]
For the next meeting we should discuss what needs to be shown based on responsiveness, cause somethings just cant be shown (unless you want to it look broken)

**Comment by Teranode** [comment]
so many browsers to test this on....

**Comment by Teranode** [comment]
I created a separate, branch for responsive edits.
